title: Soudeep Deb Research Group
description: Research, publications, consulting, alumni, and activities of Soudeep Deb's research group.

url: "https://soudeepd.github.io"
baseurl: "/soudeeps-research-group"

author:
  name: Soudeep Deb
  email: soudeep@iimb.ac.in

include:
  - _pages

header_pages:
  - _pages/research.md
  - _pages/consulting.md
  - _pages/activities.md
  - _pages/alumni.md
  - _pages/contact.md
