title: SIGNAL Lab by Prof. Soudeep Deb
description: Research, publications, consulting, and other information of Prof. Soudeep Deb's research group.

url: "https://soudeepd.github.io"
baseurl: "/soudeeps-research-group"

author:
  name: Soudeep Deb
  email: soudeep@iimb.ac.in

include:
  - _pages

header_pages:
  - _pages/research.md
  - _pages/consulting.md
  - _pages/member.md
  - _pages/alumni.md
  - _pages/news.md
  - _pages/contact.md
